# Generated by Django 4.1 on 2022-10-12 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=249)),
            ],
        ),
        migrations.CreateModel(
            name='Rabota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=249)),
                ('info', models.CharField(blank=True, max_length=249)),
                ('step1', models.CharField(blank=True, max_length=249)),
                ('photo_step1', models.ImageField(upload_to='rabota/%Y/%m/%d/')),
                ('step2', models.CharField(blank=True, max_length=249)),
                ('photo_step2', models.ImageField(upload_to='rabota/%Y/%m/%d/')),
                ('step3', models.CharField(blank=True, max_length=249)),
                ('photo_step3', models.ImageField(upload_to='rabota/%Y/%m/%d/')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.customer')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
