# Generated by Django 4.1 on 2022-10-17 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=249)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=249, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Rabota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=249, verbose_name='Название проекта')),
                ('info', models.CharField(blank=True, max_length=249, verbose_name='Задача')),
                ('project_info', models.CharField(blank=True, max_length=249, verbose_name='Инфо')),
                ('info_plan', models.CharField(blank=True, max_length=249, verbose_name='Цель')),
                ('info_finish', models.CharField(blank=True, max_length=249, verbose_name='Решение')),
                ('photo', models.ImageField(blank=True, upload_to='rabota/%Y/%m/%d', verbose_name='Фото')),
                ('step1', models.CharField(blank=True, max_length=249, verbose_name='Шаг 1')),
                ('photo_step1', models.ImageField(blank=True, upload_to='rabota/%Y/%m/%d/', verbose_name='Фото шага 1')),
                ('step2', models.CharField(blank=True, max_length=249, verbose_name='Шаг 2')),
                ('photo_step2', models.ImageField(blank=True, upload_to='rabota/%Y/%m/%d/', verbose_name='Фото шага 2')),
                ('step3', models.CharField(blank=True, max_length=249, verbose_name='Шаг 3')),
                ('photo_step3', models.ImageField(blank=True, upload_to='rabota/%Y/%m/%d/', verbose_name='Фото шага 3')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.customer', verbose_name='Заказчик')),
                ('project_type', models.ManyToManyField(blank=True, to='index.projecttype', verbose_name='Вид')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='user/avatar/%Y/%m/%d/', verbose_name='Аватарка')),
                ('doljnost', models.CharField(blank=True, max_length=49, verbose_name='Должность')),
                ('hobi', models.TextField(blank=True, verbose_name='Увлечения')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
