# Generated by Django 4.1 on 2022-10-12 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabota',
            name='info_finish',
            field=models.CharField(blank=True, max_length=249, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='info_plan',
            field=models.CharField(blank=True, max_length=249, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='info',
            field=models.CharField(blank=True, max_length=249, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='photo_step3',
            field=models.ImageField(upload_to='rabota/%Y/%m/%d/', verbose_name='Шаг 3'),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='step1',
            field=models.CharField(blank=True, max_length=249, verbose_name='Шаг 1'),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='step2',
            field=models.CharField(blank=True, max_length=249, verbose_name='Шаг 2'),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='title',
            field=models.CharField(blank=True, max_length=249, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта'),
        ),
    ]
