# Generated by Django 4.1 on 2022-10-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabota',
            name='project_type',
            field=models.ManyToManyField(blank=True, related_name='rabota_type', to='index.projecttype', verbose_name='Вид'),
        ),
    ]
