# Generated by Django 4.1 on 2022-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rabota_info_finish_rabota_info_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=249, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='rabota',
            name='project_type',
            field=models.ManyToManyField(to='index.projecttype', verbose_name='Вид'),
        ),
    ]
